/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.analizadorlexico.backend.frontend;

import com.mycompany.analizadorlexico.backend.CreadorReportes;
import com.mycompany.analizadorlexico.backend.automata.Token;
import com.mycompany.analizadorlexico.backend.automata.TokenRecuento;
import com.mycompany.analizadorlexico.backend.depurador.Depurador;
import com.mycompany.analizadorlexico.backend.depurador.Movimiento;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JTable;
import javax.swing.JTextArea;

/**
 *
 * @author edu
 */
public class DepuracionPanel extends javax.swing.JPanel {

    private CreadorReportes creadorReportes;
    private JTable tablaLexemas;
    private JTable tablaTokens;
    private JTable tablaErrores;
    private JTextArea consola;
    
    Depurador depurador;

    /**
     * Creates new form ReportesPanel
     */
    public DepuracionPanel() {
        initComponents();
        this.consola = crearConsola();
    }

    public void setDepurador(Depurador depurador) {
        consola.setText("");
        this.scrollPane.setViewportView(consola);
        this.depurador = depurador;
    }
    
    private JTextArea crearConsola() {
        JTextArea consola = new JTextArea();
        consola.setEditable(false);          
        consola.setLineWrap(true);           
        consola.setWrapStyleWord(true);      
        consola.setBackground(new Color(230, 230, 230)); 
        consola.setForeground(Color.BLACK);  // texto negro
        consola.setFont(new Font("Monospaced", Font.PLAIN, 20));
        return consola;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        retrocederBtn = new javax.swing.JButton();
        reiniciarBtn = new javax.swing.JButton();
        avanzarBtn = new javax.swing.JButton();
        avanzarAlFinalToken = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        retrocederBtn.setBackground(new java.awt.Color(204, 204, 204));
        retrocederBtn.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        retrocederBtn.setForeground(new java.awt.Color(0, 0, 0));
        retrocederBtn.setText("Retroceder (-1)");
        retrocederBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        retrocederBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retrocederBtnActionPerformed(evt);
            }
        });

        reiniciarBtn.setBackground(new java.awt.Color(153, 153, 153));
        reiniciarBtn.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        reiniciarBtn.setText("Reiniciar");
        reiniciarBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        reiniciarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reiniciarBtnActionPerformed(evt);
            }
        });

        avanzarBtn.setBackground(new java.awt.Color(204, 204, 204));
        avanzarBtn.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        avanzarBtn.setForeground(new java.awt.Color(0, 0, 0));
        avanzarBtn.setText("Avanzar (+1)");
        avanzarBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        avanzarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avanzarBtnActionPerformed(evt);
            }
        });

        avanzarAlFinalToken.setBackground(new java.awt.Color(204, 204, 204));
        avanzarAlFinalToken.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        avanzarAlFinalToken.setForeground(new java.awt.Color(0, 0, 0));
        avanzarAlFinalToken.setText("Terminar token");
        avanzarAlFinalToken.setActionCommand("");
        avanzarAlFinalToken.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        avanzarAlFinalToken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avanzarAlFinalTokenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(avanzarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(retrocederBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reiniciarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(avanzarAlFinalToken, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reiniciarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(retrocederBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(avanzarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(avanzarAlFinalToken, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        scrollPane.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void retrocederBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retrocederBtnActionPerformed
        this.consola.setText(depurador.retrocederUnPaso());
    }//GEN-LAST:event_retrocederBtnActionPerformed

    private void reiniciarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reiniciarBtnActionPerformed
       this.consola.setText(depurador.reiniciarAnalsis());
    }//GEN-LAST:event_reiniciarBtnActionPerformed

    private void avanzarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avanzarBtnActionPerformed
        this.consola.setText(depurador.avanzarUnPaso());
    }//GEN-LAST:event_avanzarBtnActionPerformed

    private void avanzarAlFinalTokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avanzarAlFinalTokenActionPerformed
        this.consola.setText(depurador.ejecutarHastaGuardarToken());
    }//GEN-LAST:event_avanzarAlFinalTokenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton avanzarAlFinalToken;
    private javax.swing.JButton avanzarBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton reiniciarBtn;
    private javax.swing.JButton retrocederBtn;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
