/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.analizadorlexico.backend.frontend;

import com.mycompany.analizadorlexico.backend.BuscadorCadenas;
import com.mycompany.analizadorlexico.backend.automata.Automata;
import com.mycompany.analizadorlexico.backend.automata.Token;
import com.mycompany.analizadorlexico.backend.depurador.Depurador;
import com.mycompany.analizadorlexico.backend.exceptions.CampoVacioException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author edu
 */
public class PanelOpciones extends javax.swing.JPanel {

    private AnalizadorFrame analizador;
    private ReportesPanel panelReportes;
    private BuscadorCadenas buscadorCadenas;
    private DepuracionPanel panelDepuracion;
    private ResultadosPanel resultadosPanel;
    /**
     * Creates new form ResultadosPanel
     */
    public PanelOpciones(AnalizadorFrame analizador,ResultadosPanel resultadosPanel, ReportesPanel panelReportes,DepuracionPanel panelDepuracion) {
        initComponents();
        this.analizador = analizador;
        this.resultadosPanel = resultadosPanel;
        this.panelReportes = panelReportes;
        this.panelDepuracion = panelDepuracion;
        this.buscadorCadenas = new BuscadorCadenas();
    }
    
    public void actualizarPosicion(int fila, int columna){
        this.posicion.setText("POSICION: "+ fila +":" + columna);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buscarBtn = new javax.swing.JButton();
        areaBusquedaText = new javax.swing.JTextField();
        analizarBtn = new javax.swing.JButton();
        limpiarBtn = new javax.swing.JButton();
        posicion = new javax.swing.JLabel();
        analizarBtn1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 153));

        buscarBtn.setBackground(new java.awt.Color(204, 204, 204));
        buscarBtn.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        buscarBtn.setText("Buscar");
        buscarBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBtnActionPerformed(evt);
            }
        });

        areaBusquedaText.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        areaBusquedaText.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        analizarBtn.setBackground(new java.awt.Color(204, 255, 204));
        analizarBtn.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        analizarBtn.setText("Analizar");
        analizarBtn.setActionCommand("");
        analizarBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        analizarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analizarBtnActionPerformed(evt);
            }
        });

        limpiarBtn.setBackground(new java.awt.Color(204, 204, 204));
        limpiarBtn.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        limpiarBtn.setText("Limpiar");
        limpiarBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        limpiarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarBtnActionPerformed(evt);
            }
        });

        posicion.setBackground(new java.awt.Color(153, 255, 153));
        posicion.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        posicion.setForeground(new java.awt.Color(0, 0, 0));
        posicion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        posicion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        analizarBtn1.setBackground(new java.awt.Color(255, 153, 153));
        analizarBtn1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        analizarBtn1.setText("Depurar");
        analizarBtn1.setActionCommand("");
        analizarBtn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        analizarBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analizarBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(buscarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(limpiarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(areaBusquedaText, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(posicion, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(analizarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(analizarBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(343, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(analizarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(analizarBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(posicion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(areaBusquedaText, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buscarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(limpiarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBtnActionPerformed
        
        String cadenaBuscada = this.areaBusquedaText.getText();
        try {
            buscadorCadenas.buscarCadena(cadenaBuscada, analizador.getEditorTextPane());
        } catch (CampoVacioException ex) {
            JOptionPane.showMessageDialog(analizador, ex.getMessage());
        }
    }//GEN-LAST:event_buscarBtnActionPerformed

    private void analizarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analizarBtnActionPerformed
        String texto = this.analizador.getEditorArea().getEditorTextPane().getText();
        Automata automata = new Automata();
            ArrayList<Token> tokens = automata.Analizar2(texto);
            this.panelReportes.crearReportes(tokens, automata.getLogs());
            this.resultadosPanel.irAlPanelReportes();
    }//GEN-LAST:event_analizarBtnActionPerformed

    private void limpiarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarBtnActionPerformed
        buscadorCadenas.limpiar(analizador.getEditorTextPane());
    }//GEN-LAST:event_limpiarBtnActionPerformed

    private void analizarBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analizarBtn1ActionPerformed
        String texto = this.analizador.getEditorArea().getEditorTextPane().getText();
        Automata automata = new Automata();
        automata.Analizar2(texto); // analizar
        Depurador depurador = new Depurador(automata.getMovimientos());
        this.panelDepuracion.setDepurador(depurador);
        this.resultadosPanel.irAlPanelDepurador();
    }//GEN-LAST:event_analizarBtn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton analizarBtn;
    private javax.swing.JButton analizarBtn1;
    private javax.swing.JTextField areaBusquedaText;
    private javax.swing.JButton buscarBtn;
    private javax.swing.JButton limpiarBtn;
    private javax.swing.JLabel posicion;
    // End of variables declaration//GEN-END:variables
}
