/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.analizadorlexico.backend.frontend;

import com.mycompany.analizadorlexico.backend.CreadorReportes;
import com.mycompany.analizadorlexico.backend.automata.Token;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edu
 */
public class ReportesPanel extends javax.swing.JPanel {

    private CreadorReportes creadorReportes;
    private JTable tablaLexemas;
    private JTable tablaTokens;
    private JTable tablaErrores;

    /**
     * Creates new form ReportesPanel
     */
    public ReportesPanel() {
        initComponents();
        this.creadorReportes = new CreadorReportes();
    }

    public void agregarTabla(ArrayList<Token> lista) {
        if(lista == null){
            return;
        }
        this.jScrollPane1.setViewportView(null);
        boolean hayErrores = this.creadorReportes.hayErrores(lista);
        boolean botonesActivos = false;

        String[] columnas = {"Tipo", "Lexema", "Fila", "Columna"};

        if (hayErrores) {
            ArrayList<Token> errores = this.creadorReportes.generarListaErrores(lista);
            this.tablaErrores = crearTabla(errores, columnas);
            this.jScrollPane1.setViewportView(tablaErrores);
        } else {

            botonesActivos = true;
            this.tablaTokens = crearTabla(creadorReportes.filtrarComentarios(lista), columnas); // se filtran los comentarios
            this.jScrollPane1.setViewportView(tablaTokens);
        }
        
        this.btnTokens.setEnabled(botonesActivos);
        this.btnRecuento.setEnabled(botonesActivos);

        this.revalidate();
        this.repaint();
        
    }

    private JTable crearTabla(ArrayList<Token> lista, String[] columnas) {
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0);
        for (Token t : lista) {
            Object[] fila = {t.getTipoToken(), t.getLexema(), t.getFila(), t.getColumna()};
            modelo.addRow(fila);
        }
        return new JTable(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRecuento = new javax.swing.JButton();
        btnTokens = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        btnRecuento.setBackground(new java.awt.Color(204, 204, 204));
        btnRecuento.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        btnRecuento.setText("Recuento Lexemas");
        btnRecuento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnRecuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecuentoActionPerformed(evt);
            }
        });

        btnTokens.setBackground(new java.awt.Color(204, 204, 204));
        btnTokens.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        btnTokens.setText("Tokens");
        btnTokens.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(228, Short.MAX_VALUE)
                .addComponent(btnRecuento, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTokens, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRecuento, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTokens, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRecuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecuentoActionPerformed

    }//GEN-LAST:event_btnRecuentoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRecuento;
    private javax.swing.JButton btnTokens;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
