/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.analizadorlexico.backend.frontend;

import com.mycompany.analizadorlexico.backend.CreadorReportes;
import com.mycompany.analizadorlexico.backend.automata.Token;
import com.mycompany.analizadorlexico.backend.automata.TokenRecuento;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edu
 */
public class ReportesPanel extends javax.swing.JPanel {

    private CreadorReportes creadorReportes;
    private JTable tablaLexemas;
    private JTable tablaTokens;
    private JTable tablaErrores;
    private JTextArea consola;

    /**
     * Creates new form ReportesPanel
     */
    public ReportesPanel() {
        initComponents();
        this.creadorReportes = new CreadorReportes();
    }

    public void crearReportes(ArrayList<Token> lista, String logs) {
        this.consola = this.crearConsola(logs);
        if(lista == null){
            return;
        }
        this.jScrollPane1.setViewportView(null);
        boolean hayErrores = this.creadorReportes.hayErrores(lista);
        boolean botonesActivos = false;

        String[] columnas = {"Tipo", "Lexema", "Fila", "Columna"};

        if (hayErrores) {
            ArrayList<Token> errores = this.creadorReportes.generarListaErrores(lista);
            this.tablaErrores = crearTablaErrores(errores);
            this.jScrollPane1.setViewportView(tablaErrores);
        } else {

            botonesActivos = true;
            this.tablaLexemas = crearTablaLexemas(creadorReportes.generarRecuentoLexemas(creadorReportes.filtrarComentarios(lista)));
            this.tablaTokens = crearTablaTokens(creadorReportes.filtrarComentarios(lista)); // se filtran los comentarios
            this.jScrollPane1.setViewportView(tablaTokens);
        }
        
        this.btnTokens.setEnabled(botonesActivos);
        this.btnRecuento.setEnabled(botonesActivos);

        this.revalidate();
        this.repaint();
        
    }

    private JTable crearTablaTokens(ArrayList<Token> lista) {
        String[] columnas = {"Tipo", "Lexema", "Fila", "Columna"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0);
        for (Token t : lista) {
            Object[] fila = {t.getTipoToken(), t.getLexema(), t.getFila(), t.getColumna()};
            modelo.addRow(fila);
        }
        return new JTable(modelo);
    }
    
    private JTable crearTablaLexemas(ArrayList<TokenRecuento> lista) {
        String[] columnas = { "Lexema","Tipo","Cantidad: "};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0);
        for (TokenRecuento t : lista) {
            Object[] fila = { t.getLexema(),t.getTipoToken(), t.getCantidad()};
            modelo.addRow(fila);
        }
        return new JTable(modelo);
    }
    
    
    private JTable crearTablaErrores(ArrayList<Token> lista) {
        String[] columnas = {"Error", "Fila", "Columna", "Esperado: "};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0);
        for (Token t : lista) {
            Object[] fila = { t.getLexema(),t.getFila(), t.getColumna(), t.getMensaje()};
            modelo.addRow(fila);
        }
        return new JTable(modelo);
    }
    
    private JTextArea crearConsola(String contenido) {
        JTextArea consola = new JTextArea();
        consola.setEditable(false);          
        consola.setLineWrap(true);           
        consola.setWrapStyleWord(true);      
        consola.setBackground(new Color(230, 230, 230)); 
        consola.setForeground(Color.BLACK);  // texto negro
        consola.setFont(new Font("Monospaced", Font.PLAIN, 20));
        consola.append(contenido);
        return consola;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRecuento = new javax.swing.JButton();
        btnTokens = new javax.swing.JButton();
        consolaBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        btnRecuento.setBackground(new java.awt.Color(204, 204, 204));
        btnRecuento.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        btnRecuento.setText("Recuento Lexemas");
        btnRecuento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnRecuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecuentoActionPerformed(evt);
            }
        });

        btnTokens.setBackground(new java.awt.Color(204, 204, 204));
        btnTokens.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        btnTokens.setText("Tokens");
        btnTokens.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnTokens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTokensActionPerformed(evt);
            }
        });

        consolaBtn.setBackground(new java.awt.Color(204, 255, 204));
        consolaBtn.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        consolaBtn.setText("Consola");
        consolaBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        consolaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consolaBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(consolaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRecuento, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTokens, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTokens, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRecuento, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consolaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRecuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecuentoActionPerformed
        this.jScrollPane1.setViewportView(tablaLexemas);
    }//GEN-LAST:event_btnRecuentoActionPerformed

    private void btnTokensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTokensActionPerformed
       this.jScrollPane1.setViewportView(tablaTokens);
    }//GEN-LAST:event_btnTokensActionPerformed

    private void consolaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consolaBtnActionPerformed
        this.jScrollPane1.setViewportView(consola);
    }//GEN-LAST:event_consolaBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRecuento;
    private javax.swing.JButton btnTokens;
    private javax.swing.JButton consolaBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
